### PR TITLE
Changed gender and sex ambiguities / Fixed typos

### PR DESCRIPTION
**Pull request by ismayc**
Fixed typo

### CODE REVIEW

**Comment by ismayc** [comment]
Gender is masculine / feminine. Sex is male / female. Also switched to non-binary language instead of intersex. http://www.med.monash.edu.au/gendermed/sexandgender.html

**Comment by ncarchedi** [comment]
@richierocks Can you review and merge these changes into your branch (#25) when you have a moment?

**Comment by richierocks** [comment]
@ncarchedi 

I made a more extensive rewrite of the exercises regarding gender/sex in the other pull request, so these fixes are no longer needed. (I hadn't realized someone else was working on this.)

In my version of the fix, I keep `Male` and `Female`, but change the variable to `sex_vector`, and mention that there are several situations where you need more than two categories.

**Comment by richierocks** [comment]
@ismayc 

Thanks for your work on this; I'm not merging, but the sex/gender issue is being addressed.

**Comment by ismayc** [comment]
Thanks!  I look forward to reviewing the changes.

**Pull request closed without merging**
